services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGIN=http://localhost:3000  # Assuming the frontend runs on localhost:3000
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000  # Use the service name for internal Docker networking
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
