services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - CORS_ORIGIN=https://wisewalletwin.com  # Assuming the frontend runs on localhost:3000
      - SECRET_KEY
      - DATABASE_URL
    env_file:
      - .env
    
    networks:
      - app-network

volumes:
  backend-data:

networks:
  app-network:
    driver: bridge
