services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGIN=https://wisewalletwin.com  # Assuming the frontend runs on localhost:3000
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - backend-data:/data
    networks:
      - app-network

volumes:
  backend-data:

networks:
  app-network:
    driver: bridge
