services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGIN=https://wisewalletwin.com  # Assuming the frontend runs on localhost:3000
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - backend-data:/data
    networks:
      - app-network

  frontend:
    build: ./frontend
    environment:
      - API_URL=https://api.wisewalletwin.com # Use the service name for internal Docker networking
    depends_on:
      - backend
    networks:
      - app-network

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./Frontend/build:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  backend-data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
