name: my-app
services:
  - name: backend
    dockerfile_path: backend/Dockerfile
    github:
      repo: hellomottoworld/SpendSmart
      branch: main
    http_port: 8000
    environment_variables:
      - key: CORS_ORIGIN
        value: http://localhost:3000  # Adjust this to the actual frontend URL in production

  - name: frontend
    dockerfile_path: frontend/Dockerfile
    github:
      repo: hellomottoworld/SpendSmart
      branch: main
    http_port: 3000
    environment_variables:
      - key: API_URL
        value: http://backend:8000
