name: Super-Linter

on: push

jobs: 
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: List files in the workspace
        run: ls -la ${{ github.workspace }}

      - name: Super-Linter
        uses:  super-linter/super-linter@v5.7.2
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_MYPY: true
          PYTHON_MYPY_CONFIG_FILE: ${{ github.workspace }}/mypy.ini


