name: Super-Linter

on: push

jobs: 
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-Linter
        uses:  super-linter/super-linter@v5.7.2
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_MYPY: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'  # Specify the Python version

      - name: Install Mypy
        run: pip install mypy

      - name: Run Mypy
        run: mypy . --config-file mypy.ini


