name: Super-Linter

on: push

jobs: 
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Set up Python
        uses: actions/setup-python@v5.1.0

      - name: Python Black
        uses: cytopia/docker-black@0.11
        with:
          path: .

      - name: Format code with Black
        run: black . 
        continue-on-error: true
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes if needed
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff --exit-code || git commit -m "Apply black formatting"
            git push
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        

      - name: Set up Environment for Super-Linter
        uses: actions/setup-node@v4.0.2

      - name: Run Super-Linter
        uses:  super-linter/super-linter@v5.7.2
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_MYPY: false
        continue-on-error: true


